-- begin SAMPLECHECKLIST_OPTION
alter table SAMPLECHECKLIST_OPTION add constraint FK_SAMPLECHECKLIST_OPTION_GROUP foreign key (GROUP_ID) references SAMPLECHECKLIST_OPTIONS_GROUP(ID)^
create index IDX_SAMPLECHECKLIST_OPTION_GROUP on SAMPLECHECKLIST_OPTION (GROUP_ID)^
-- end SAMPLECHECKLIST_OPTION
-- begin SAMPLECHECKLIST_CHECK
alter table SAMPLECHECKLIST_CHECK add constraint FK_SAMPLECHECKLIST_CHECK_GROUP foreign key (GROUP_ID) references SAMPLECHECKLIST_CHECKS_GROUP(ID)^
alter table SAMPLECHECKLIST_CHECK add constraint FK_SAMPLECHECKLIST_CHECK_OPTIONS_GROUP foreign key (OPTIONS_GROUP_ID) references SAMPLECHECKLIST_OPTIONS_GROUP(ID)^
create index IDX_SAMPLECHECKLIST_CHECK_GROUP on SAMPLECHECKLIST_CHECK (GROUP_ID)^
create index IDX_SAMPLECHECKLIST_CHECK_OPTIONS_GROUP on SAMPLECHECKLIST_CHECK (OPTIONS_GROUP_ID)^
-- end SAMPLECHECKLIST_CHECK
-- begin SAMPLECHECKLIST_CHECK_ITEM
alter table SAMPLECHECKLIST_CHECK_ITEM add constraint FK_SAMPLECHECKLIST_CHECK_ITEM_CHECK foreign key (CHECK_ID) references SAMPLECHECKLIST_CHECK(ID)^
alter table SAMPLECHECKLIST_CHECK_ITEM add constraint FK_SAMPLECHECKLIST_CHECK_ITEM_OPTION foreign key (OPTION_ID) references SAMPLECHECKLIST_OPTION(ID)^
alter table SAMPLECHECKLIST_CHECK_ITEM add constraint FK_SAMPLECHECKLIST_CHECK_ITEM_LOAN_APPLICATION foreign key (LOAN_APPLICATION_ID) references SAMPLECHECKLIST_LOAN_APPLICATION(ID)^
create index IDX_SAMPLECHECKLIST_CHECK_ITEM_CHECK on SAMPLECHECKLIST_CHECK_ITEM (CHECK_ID)^
create index IDX_SAMPLECHECKLIST_CHECK_ITEM_OPTION on SAMPLECHECKLIST_CHECK_ITEM (OPTION_ID)^
create index IDX_SAMPLECHECKLIST_CHECK_ITEM_LOAN_APPLICATION on SAMPLECHECKLIST_CHECK_ITEM (LOAN_APPLICATION_ID)^
-- end SAMPLECHECKLIST_CHECK_ITEM
