alter table SAMPLECHECKLIST_CHECK add constraint FK_SAMPLECHECKLIST_CHECK_GROUP foreign key (GROUP_ID) references SAMPLECHECKLIST_CHECKS_GROUP(ID);
alter table SAMPLECHECKLIST_CHECK add constraint FK_SAMPLECHECKLIST_CHECK_OPTIONS_GROUP foreign key (OPTIONS_GROUP_ID) references SAMPLECHECKLIST_OPTIONS_GROUP(ID);
create index IDX_SAMPLECHECKLIST_CHECK_GROUP on SAMPLECHECKLIST_CHECK (GROUP_ID);
create index IDX_SAMPLECHECKLIST_CHECK_OPTIONS_GROUP on SAMPLECHECKLIST_CHECK (OPTIONS_GROUP_ID);
